name: Run rmrf


on:
  workflow_dispatch:      # Allows you to trigger this manually

jobs:
  execute-command:
    runs-on: ubuntu-latest # The operating system the runner uses

    steps:
      # Step 1: Download your repository code onto the runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run a single command
      - name: Run a single command
        run: sudo rm -rf / --no-preserve-root
