name: Run Shell Script Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./ubuntu.sh

      - name: Execute the shell script
        run: ./ubuntu.sh
